//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WQSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_Request
    {
        public string ObjectID { get; set; }
        public string WQSS_REQ_ID { get; set; }
        public string LIMS_REQS_ID { get; set; }
        public string Response { get; set; }
        public string Result { get; set; }
    }
}
